Sprint 1
Alexander-Prokhorov/aprokhorov-praktikum pull request #1
Opened 2022-05-28 19:20 UTC by Alexander-Prokhorov

2022-06-01 20:52 UTC, ASPecherkin requested changes
оставил несколько замечаний

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/agent/main.go
> +	"aprokhorov-praktikum/cmd/agent/poller"
замечение/совет к стилю - лучше установить и настроить с IDE https://golangci-lint.run/usage/install/ и goimports , чтобы в Go файлов импорты пакетов были стилистически одинаковыми 

зачем это нужно - Во всех компаниях/ репозиториях принят тот или иной порядок импорта пакетов

чаще всего это
- stdlib
- пакеты приложения
- внешние зависимости

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/agent/main.go
> +	conf := Config{
лучше вынести в отдельный конструктор Config 
и дальше эту функцию вместе со структурой 
```go
type Config struct 
```

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/agent/sender/sender.go
> +	s.Client = http.Client{}
архитектруное замечание:
лучше стараться не использоваться http клиент без настроек 

как минимум нужно проставлять timeout  , чтобы не получить зависшее из-за медленной сети приложение

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/server/handlers/handler_post_test.go
> +package handlers_test
ты можешь названия файлов в этом пакете упростить до get/post и тесты соотвественно 

Потому что там где они будут использоваться - там будет название пакета перед ними 
вида
```go
smth := handlers.Get(smth)
```

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/server/storage/mem-storage.go
> +	ms.Metrics.Gauge = make(map[string]Gauge)
по-хорошему эта проблема есть и у сервера и у клиента, просто на сервере она наиболее вероятна при записи метрик 

Это не описано в курсе, но конкуретная запись в map приводит к панике в приложении 

Конкуретное чтение при конкуретной записи может привести к проблеме с консистентностью данных 

Как можно этого избежать хорошо описано тут - Ещё момент - так как возможна конкуретная запись в map - то проихойдёт паника
подробнее можно почитать тут - https://medium.com/@luanrubensf/concurrent-map-access-in-go-a6a733c5ffd1

поэтому лучше использовать sync.RwMutex в паре с map

2022-06-01 20:52 UTC, ASPecherkin commented on cmd/server/storage/storage.go
> +	Init()
вопрос - а с какой целью такой метод вынесен в интерфейс описания функциональности хранилища?

2022-06-02 08:12 UTC, Alexander-Prokhorov commented on cmd/agent/main.go
> +	"aprokhorov-praktikum/cmd/agent/poller"
Поменял в VSCode линтеры на golangci-lint и gofmt на goimports, но формат импортов остался тот же. Пока не понял как нужно настроить порядок в import'ах. По дефолту сортирует в 
- Пакеты приложения
- stdlib
- внешние

2022-06-02 08:16 UTC, Alexander-Prokhorov commented on cmd/agent/main.go
> +	conf := Config{
Понял, переделаю

2022-06-02 08:20 UTC, Alexander-Prokhorov commented on cmd/server/storage/storage.go
> +	Init()
Сделал так потому что в тестах использую интерфейс хранилища, и там использую Init.
В тестах лучше использовать не интерфейс, а конкретную реализацию, или можно оставить так, или какой лучше выход?

2022-06-02 08:30 UTC, Alexander-Prokhorov commented on cmd/agent/sender/sender.go
> +	s.Client = http.Client{}
Понял, добавлю

2022-06-02 08:30 UTC, Alexander-Prokhorov commented on cmd/server/handlers/handler_post_test.go
> +package handlers_test
Точно, спасибо, сделал

2022-06-02 20:35 UTC, ASPecherkin commented on cmd/server/storage/storage.go
> +	Init()
в тестах можно использовать конкретную имплиментацию или уже готовый мок 

Отдельно метод конструктора в интерфейс можно не выносить

2022-06-02 20:40 UTC, ASPecherkin approved these changes
есть небольшие огрехи, которые можно будет потом поправить в будущих PR 
или если не понятно как это делать - спросить на 1-2-1

2022-06-02 20:40 UTC, ASPecherkin commented on cmd/agent/poller/poller.go
> +	p.Storage = new(storage.MemStorage)
Вообще этот метод можно вытащить в метод вида 
```go
func NewPoller(db storage.Storage)
и для db что-то вида 
db := NewMemoryStorage()
```
и уже в каждом из них будут проставлены default значения, которые нужно 
Не принципиально, можно сделать в будущем

2022-06-02 20:40 UTC, ASPecherkin commented on cmd/agent/sender/sender.go
> +	s.Client = http.Client{
отлично, так будет работать надёжнее

2022-06-11 09:34 UTC, merged