Increment 4. Add Json
Alexander-Prokhorov/aprokhorov-praktikum pull request #2
Opened 2022-06-13 08:00 UTC by Alexander-Prokhorov

2022-06-21 21:32 UTC, ASPecherkin requested changes
есть комментарий на тему глобальной переменной и композиции

2022-06-21 21:32 UTC, ASPecherkin commented on cmd/agent/main.go
> +func init() {
стилистический и комментарий к композиции , который направлен на тему глобальной переменной и как от неё отказаться 

лучше сделать init конфигурации явно и вынести его в main 
и далее результат ```conf``` передавать туда , где он необходим

2022-06-25 09:55 UTC, Alexander-Prokhorov commented on cmd/agent/main.go
> +func init() {
Поправил тут, но не понял как использовать тогда flag в связке с Init.
Подумал что так тоже не надо делать, и перенес объявления flag в main тоже.

2022-06-25 22:15 UTC, ASPecherkin approved these changes

2022-06-26 09:09 UTC, merged