Sprit-3
Alexander-Prokhorov/aprokhorov-praktikum pull request #3
Opened 2022-06-28 20:29 UTC by Alexander-Prokhorov

2022-07-06 18:01 UTC, blattaria7 requested changes
Отличная работа!) Мне очень нравится как выполнено задание!

Оставила тут немного рекомендаций, их нужно добавить. Если будут вопросы - пиши, ставь 1-1)

2022-07-06 18:01 UTC, blacknoire7 commented on cmd/agent/sender/sender.go
>  	case "counter":
можно кстати `counter` и `gauge` вынести в константы, раз они много где используются) и обращаться по ним)

2022-07-06 18:01 UTC, blacknoire7 commented on cmd/server/handlers/json-update.go
> +			err := updateHelper(w, s, &metric, key)
вот так опасно делать)

здесь хорошо написано почему https://stackoverflow.com/questions/62446118/implicit-memory-aliasing-in-for-loop

2022-07-06 18:01 UTC, blacknoire7 commented on internal/hasher/hasher_test.go
> +			if got != string(tt.want) {
переменная`tt.want` тут и так строка (на 26 строке она определяется как строка), так что можно опустить это приведение)

2022-07-06 18:01 UTC, blacknoire7 commented on cmd/agent/main.go
> +				go func(metric map[string]map[string]string, key string) {
не очень понимаю почему тут `metric map[string]map[string]string` передается в аргументах, если горутина получает переменную, которая выше?

2022-07-06 18:01 UTC, blacknoire7 commented on internal/storage/postgres.go
> +	ctx        context.Context
нельзя передавать контекст в поле структуры, это противоречит его идее)

он должен передаваться в аргументы функций из методов, в которых эти функции вызываются
вот статейка на эту тему https://habr.com/ru/post/269299/

2022-07-06 18:01 UTC, blacknoire7 commented on cmd/server/handlers/helpers.go
> +		resultValue := value.(storage.Counter) + storage.Counter(newValue)
приводя переменную к типу обязательно нужно делать проверку на то, что приведение прошло успешно

```go
oldValue, ok := value.(storage.Counter)
if !ok {
	// ...
}
		
resultValue :=  oldValue +  storage.Counter(newValue)
```

2022-07-12 15:52 UTC, Alexander-Prokhorov commented on cmd/agent/sender/sender.go
>  	case "counter":
Добавил тут и в server-части, где имело смысл, кмк

2022-07-12 15:52 UTC, Alexander-Prokhorov commented on cmd/server/handlers/json-update.go
> +			err := updateHelper(w, s, &metric, key)
поменял тут

2022-07-12 15:53 UTC, Alexander-Prokhorov commented on internal/hasher/hasher_test.go
> +			if got != string(tt.want) {
Ага, действительно, поправил, спасибо.

2022-07-12 15:54 UTC, Alexander-Prokhorov commented on cmd/agent/main.go
> +				go func(metric map[string]map[string]string, key string) {
Да, опечатался, поправил. Но тут все равно вопрос как лучше в таких моментах поступал, передавать копией, или переменной которая выше?

2022-07-12 15:54 UTC, Alexander-Prokhorov commented on internal/storage/postgres.go
> +	ctx        context.Context
Выпилил пока контекст, все равно не использую как следует, кмк. 
Лучше добавлю если потребуется в следующем спринте.

2022-07-12 15:55 UTC, Alexander-Prokhorov commented on cmd/server/handlers/helpers.go
> +		resultValue := value.(storage.Counter) + storage.Counter(newValue)
Добавил, спасибо!

2022-07-12 21:29 UTC, blattaria7 commented on cmd/agent/main.go
> +				go func(metric map[string]map[string]string, key string) {
лучше переменной, которая выше, чтобы поменьше дублей было)

2022-07-12 21:48 UTC, blattaria7 approved these changes
Работу принимаю =)

2022-07-16 14:38 UTC, merged